/* RCT OpsDesk — Script Library (js/scripts.js)
 *
 * Searchable PowerShell script registry for the Guided Audit wizard.
 * - Two built-in extraction scripts ship with the app (verbatim .ps1 sources).
 * - Custom scripts are added through the Scripts overlay and stored in
 *   browser localStorage (per site); export/import JSON moves them between sites.
 * - The wizard's copy buttons pre-fill the school's tenant ID from the GDAP
 *   mapping when it matches. The dashboard never executes PowerShell.
 *
 * Generated by tools/gen-scripts-module.py — do not hand-edit the bodies.
 */
var QBR = (window.QBR = window.QBR || {});
(function () {
  "use strict";

  var LS_KEY = "qbr.scripts.custom.v1";

  /* ------------------------------------------------------------------ */
  /* Built-in scripts (bodies generated verbatim from the .ps1 sources).  */
  /* ------------------------------------------------------------------ */
  var BUILTINS = [
    {
      id: "storage",
      title: "Storage Extraction",
      tags: "extract, storage, onedrive, sharepoint, exchange, m365",
      desc: "Tenant storage report via Microsoft Graph (OneDrive, SharePoint, Exchange). Produces the 7 values for the Storage paste step.",
      body: `<#
============================================================
Bulk Extract M365 Storage Report - Phased Execution
============================================================
Description:
- Designed for copy-paste execution into a PowerShell terminal
- Runs in 5 distinct phases with user confirmation
- Pulls tenant-wide storage from Microsoft Graph (period=D30)
- Consolidates into a 3-row / 5-column CSV (one row per service)

Endpoints pulled (in parallel, PS7+):
  1. getOneDriveUsageAccountDetail(period='D30')   -> per-user OneDrive
  2. getSharePointSiteUsageDetail(period='D30')    -> per-site SharePoint
  3. getMailboxUsageDetail(period='D30')           -> per-mailbox Exchange

Output columns (exact 7 columns, single row):
  ONEDRIVE, EXCHANGE, SHARE POINT, CURRENT STORAGE ( <MONTH>),
  USAGE, Used Storage(GB), Total Storage(GB)

Column semantics:
  ONEDRIVE                = OneDrive used (human-readable size)
  EXCHANGE                = Exchange used (human-readable size)
  SHARE POINT             = SharePoint used (human-readable size)
  CURRENT STORAGE ( <MONTH>) = Combined used across all 3 (human-readable size)
                            <MONTH> derives from the run date; overridable at the prompt.
  USAGE                   = "<X.XX> TB of <Y.YY> TB used" (pooled TB fraction)
  Used Storage(GB)        = Combined used, numeric GB (2 decimals)
  Total Storage(GB)       = Combined quota, numeric GB (2 decimals)

Sizing notes:
- Used  = sum of "Storage Used (Byte)" across active (non-deleted) rows
- Total = sum of "Storage Allocated (Byte)" for OneDrive / SharePoint
       = sum of "Prohibit Send/Receive Quota (Byte)" for Exchange
- Binary GB (1 GB = 1024^3 bytes) - matches Microsoft admin center portal
- Deleted accounts/sites/mailboxes are excluded (Is Deleted = False)

Requirements:
- PowerShell 7+
- Microsoft.Graph.Authentication module
- Admin role: Reports Reader / Global Reader / Global Admin
- Scopes: Reports.Read.All, Organization.Read.All

How to use:
- Copy-paste each phase into a PowerShell 7+ terminal
- OR paste the entire script at once

.AUTHOR         Generated with Claude for Rakso CT Education IT.
.VERSION        2.0
.DATE           2026-08-19
.REQUIREMENTS   PowerShell 7+ (parallel pull); Microsoft.Graph.Authentication.
.PERMISSIONS    Reports.Read.All, Organization.Read.All (both read-only).
.SAFETY         Read-only. Pulls usage reports only; nothing is written to the tenant.
.CHANGELOG      v1.0 - Initial release.
                v2.0 - Removed the hardcoded tenant GUID and the hardcoded output
                       folder. Tenant ID is prompted and GUID-validated at runtime;
                       the output folder defaults to the script's own folder and stays
                       overridable. The snapshot column label, previously frozen at
                       "CURRENT STORAGE ( JUNE)", now derives from the run month and
                       can be overridden - the old build mislabelled the column on
                       every run outside June.
============================================================
#>


# ============================================================
# PHASE 1 - Configure Paths + Period
# ============================================================
Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host " PHASE 1: Configure Paths + Period" -ForegroundColor Cyan
Write-Host "============================================================" -ForegroundColor Cyan

# Helper: strip invisible/Unicode formatting chars from pasted paths
function Remove-InvisibleChars {
    param([string]$s)
    if ([string]::IsNullOrEmpty($s)) { return $s }
    return ($s -replace '[\\u200B-\\u200F\\u202A-\\u202E\\u2066-\\u2069\\uFEFF\\u00A0\\u202F\\u1680\\u2000-\\u200A\\u205F\\u3000]', '')
}

# --- Dynamic path defaults ---------------------------------------------------
# No machine-specific path is stored in this file. Defaults resolve at runtime to
# the script's own folder. When the script is pasted block-by-block into a
# terminal $PSScriptRoot is empty, so the current working directory is used.
# Every default is still overridable at the prompt.
$ScriptDir = ''
try { if ($PSScriptRoot) { $ScriptDir = $PSScriptRoot } } catch { }
if (-not $ScriptDir) {
    try {
        if ($MyInvocation.MyCommand.Path) { $ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path }
    } catch { }
}
if (-not $ScriptDir) { $ScriptDir = (Get-Location).Path }

$DefaultOutputFolder = Join-Path $ScriptDir 'Reports'
$Period = "D30"

Write-Host ""
Write-Host "Default output folder:" -ForegroundColor Gray
Write-Host "  $DefaultOutputFolder" -ForegroundColor DarkGray
$InputFolder = Read-Host "Enter output folder (or press Enter to use default)"
if ([string]::IsNullOrWhiteSpace($InputFolder)) {
    $OutputFolder = $DefaultOutputFolder
} else {
    $OutputFolder = (Remove-InvisibleChars $InputFolder).Trim('"').Trim("'").Trim()
}

# Create folder if missing
if (-not (Test-Path -LiteralPath $OutputFolder)) {
    try {
        New-Item -Path $OutputFolder -ItemType Directory -Force | Out-Null
        Write-Host "Created output folder: $OutputFolder" -ForegroundColor DarkGray
    } catch {
        Write-Host "ERROR: Could not create folder '$OutputFolder': $($_.Exception.Message)" -ForegroundColor Red
        return
    }
}

# Timestamped output path
$TimeStamp  = Get-Date -Format "yyyyMMdd_HHmmss"
$OutputPath = Join-Path -Path $OutputFolder -ChildPath "M365_StorageReport_\${Period}_$TimeStamp.csv"

# Snapshot column label. v1.0 froze this at "CURRENT STORAGE ( JUNE)", so every
# report run outside June shipped with a wrong month on the column. It now derives
# from the run date and can still be overridden (e.g. to label a back-dated pull).
$DefaultMonthLabel = (Get-Date).ToString('MMMM').ToUpperInvariant()
Write-Host ""
$InputMonthLabel = Read-Host "Snapshot month label for the storage column (Enter = $DefaultMonthLabel)"
$MonthLabel = if ([string]::IsNullOrWhiteSpace($InputMonthLabel)) { $DefaultMonthLabel } else { (Remove-InvisibleChars $InputMonthLabel).Trim().ToUpperInvariant() }
$CurrentStorageCol = "CURRENT STORAGE ( $MonthLabel)"

Write-Host ""
Write-Host "Configuration:" -ForegroundColor Green
Write-Host "  Period          : $Period (past 30 days)" -ForegroundColor Green
Write-Host "  Snapshot column : $CurrentStorageCol" -ForegroundColor Green
Write-Host "  Output CSV      : $OutputPath" -ForegroundColor Green


# ============================================================
# PHASE 2 - Connect to Microsoft Graph (Tenant ID + Sign-In Mode)
# ============================================================
Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host " PHASE 2: Connect to Microsoft Graph" -ForegroundColor Cyan
Write-Host "============================================================" -ForegroundColor Cyan

# Require PS7+
if ($PSVersionTable.PSVersion.Major -lt 7) {
    Write-Host ""
    Write-Host "ERROR: PowerShell 7+ is required (parallel processing)." -ForegroundColor Red
    Write-Host "Current version: $($PSVersionTable.PSVersion)" -ForegroundColor Red
    return
}

# Ensure Microsoft.Graph.Authentication is present
if (-not (Get-Module -ListAvailable -Name Microsoft.Graph.Authentication)) {
    Write-Host ""
    Write-Host "ERROR: Microsoft.Graph.Authentication module not installed." -ForegroundColor Red
    Write-Host "Install with:" -ForegroundColor Yellow
    Write-Host "  Install-Module Microsoft.Graph -Scope CurrentUser -Force" -ForegroundColor Yellow
    return
}
try {
    Import-Module Microsoft.Graph.Authentication -ErrorAction Stop
} catch {
    Write-Host "ERROR: Failed to import module: $($_.Exception.Message)" -ForegroundColor Red
    return
}

# --- Tenant ID ---------------------------------------------------------------
# Prompted at runtime and never stored in this file, so the script is safe to
# commit and safe to hand to another admin or another tenant.
Write-Host ""
$InputTenantId = Read-Host "Enter Tenant ID (GUID)"
$TenantId = (Remove-InvisibleChars $InputTenantId).Trim().Trim('"').Trim("'").Trim()
if ([string]::IsNullOrWhiteSpace($TenantId)) {
    Write-Host "ERROR: Tenant ID is required." -ForegroundColor Red
    return
}
if ($TenantId -notmatch '^[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}$') {
    Write-Host "ERROR: '$TenantId' is not a valid GUID." -ForegroundColor Red
    Write-Host "  Find it in the Entra admin center > Overview > Tenant ID." -ForegroundColor Yellow
    return
}

# Sign-in mode
Write-Host ""
Write-Host "Sign-in modes:" -ForegroundColor Yellow
Write-Host "  [1] Browser / DeviceCode flow (default)" -ForegroundColor DarkGray
Write-Host "  [2] Interactive popup" -ForegroundColor DarkGray
Write-Host "  [3] Reuse existing session" -ForegroundColor DarkGray
$SignInMode = Read-Host "Select sign-in mode (1/2/3, Enter=1)"
if ([string]::IsNullOrWhiteSpace($SignInMode)) { $SignInMode = "1" }

$Scopes = @("Reports.Read.All","Organization.Read.All")

try {
    switch ($SignInMode) {
        "2" {
            Write-Host ""
            Write-Host "Connecting via Interactive popup..." -ForegroundColor Cyan
            Connect-MgGraph -TenantId $TenantId -Scopes $Scopes -NoWelcome -ErrorAction Stop
        }
        "3" {
            $ExistingCtx = Get-MgContext
            if (-not $ExistingCtx) {
                Write-Host ""
                Write-Host "No existing session. Falling back to DeviceCode." -ForegroundColor Yellow
                Connect-MgGraph -TenantId $TenantId -Scopes $Scopes -UseDeviceCode -NoWelcome -ErrorAction Stop
            } else {
                Write-Host ""
                Write-Host "Reusing existing session: $($ExistingCtx.Account)" -ForegroundColor Green
            }
        }
        default {
            Write-Host ""
            Write-Host "Connecting via DeviceCode flow..." -ForegroundColor Cyan
            Connect-MgGraph -TenantId $TenantId -Scopes $Scopes -UseDeviceCode -NoWelcome -ErrorAction Stop
        }
    }

    $Context = Get-MgContext
    if (-not $Context) { throw "No Graph context after Connect-MgGraph." }

    Write-Host ""
    Write-Host "Connected successfully." -ForegroundColor Green
    Write-Host "  Account : $($Context.Account)" -ForegroundColor DarkGray
    Write-Host "  Tenant  : $($Context.TenantId)" -ForegroundColor DarkGray
    Write-Host "  Scopes  : $($Context.Scopes -join ', ')" -ForegroundColor DarkGray
}
catch {
    Write-Host "ERROR: Failed to connect: $($_.Exception.Message)" -ForegroundColor Red
    return
}


# ============================================================
# PHASE 3 - Preview Endpoints + Scope Check
# ============================================================
Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host " PHASE 3: Preview Endpoints + Scope Check" -ForegroundColor Cyan
Write-Host "============================================================" -ForegroundColor Cyan

$Endpoints = @(
    [PSCustomObject]@{ Name="OneDrive";   Uri="https://graph.microsoft.com/v1.0/reports/getOneDriveUsageAccountDetail(period='$Period')" }
    [PSCustomObject]@{ Name="SharePoint"; Uri="https://graph.microsoft.com/v1.0/reports/getSharePointSiteUsageDetail(period='$Period')" }
    [PSCustomObject]@{ Name="Exchange";   Uri="https://graph.microsoft.com/v1.0/reports/getMailboxUsageDetail(period='$Period')" }
)

Write-Host ""
Write-Host "Reports to pull (parallel, ThrottleLimit=3):" -ForegroundColor Yellow
$Endpoints | Format-Table Name, Uri -AutoSize | Out-Host

# Scope validation
$RequiredScopes = @("Reports.Read.All","Organization.Read.All")
$GrantedScopes  = @($Context.Scopes)
$MissingScopes  = $RequiredScopes | Where-Object { $_ -notin $GrantedScopes }

if ($MissingScopes.Count -gt 0) {
    Write-Host "WARNING: Missing scopes: $($MissingScopes -join ', ')" -ForegroundColor Yellow
    Write-Host "Some reports may fail. Reconnect with the missing scopes if needed." -ForegroundColor Yellow
} else {
    Write-Host "All required scopes granted." -ForegroundColor Green
}


# ============================================================
# PHASE 4 - Confirmation
# ============================================================
Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host " PHASE 4: Confirmation" -ForegroundColor Cyan
Write-Host "============================================================" -ForegroundColor Cyan

Write-Host ""
Write-Host "Summary:" -ForegroundColor Yellow
Write-Host "  Tenant ID    : $TenantId" -ForegroundColor DarkGray
Write-Host "  Account      : $($Context.Account)" -ForegroundColor DarkGray
Write-Host "  Period       : $Period" -ForegroundColor DarkGray
Write-Host "  Endpoints    : $($Endpoints.Count)" -ForegroundColor DarkGray
Write-Host "  Output CSV   : $OutputPath" -ForegroundColor DarkGray
Write-Host ""

$Confirm = Read-Host "Proceed to pull reports? (Y/N)"
if ($Confirm -notmatch '^(y|yes)$') {
    Write-Host ""
    Write-Host "Operation cancelled by user. No changes were made." -ForegroundColor Red
    Write-Host "Disconnecting..." -ForegroundColor DarkGray
    Disconnect-MgGraph -ErrorAction SilentlyContinue | Out-Null
    return
}


# ============================================================
# PHASE 5 - Parallel Pull + Aggregate + Export
# ============================================================
Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host " PHASE 5: Pull Reports in Parallel + Export" -ForegroundColor Cyan
Write-Host "============================================================" -ForegroundColor Cyan

# ------------------------------------------------------------
# Acquire raw access token for parallel REST calls.
# ------------------------------------------------------------
try {
    $TokenResp = Invoke-MgGraphRequest  -Method GET  -Uri "https://graph.microsoft.com/v1.0/organization"  -OutputType HttpResponseMessage  -ErrorAction Stop
    $AccessToken = $TokenResp.RequestMessage.Headers.Authorization.Parameter
    if ([string]::IsNullOrWhiteSpace($AccessToken)) { throw "Empty access token" }
    Write-Host "Access token acquired for parallel calls." -ForegroundColor Green
} catch {
    Write-Host "ERROR: Could not acquire access token: $($_.Exception.Message)" -ForegroundColor Red
    Disconnect-MgGraph -ErrorAction SilentlyContinue | Out-Null
    return
}

Write-Host ""
Write-Host "Pulling $($Endpoints.Count) endpoints in parallel..." -ForegroundColor Cyan

$Results = $Endpoints | ForEach-Object -Parallel {
    $ep         = $_
    $token      = $using:AccessToken
    $maxRetries = 5
    $headers    = @{ Authorization = "Bearer $token" }

    $success = $false
    $errMsg  = $null
    $content = $null

    for ($i = 0; $i -lt $maxRetries; $i++) {
        try {
            $resp = Invoke-WebRequest -Uri $ep.Uri -Headers $headers -UseBasicParsing -ErrorAction Stop

            # Graph returns CSV as byte[] (Content-Type: application/octet-stream).
            # Normalize to UTF-8 string + strip BOM.
            if ($resp.Content -is [byte[]]) {
                $content = [System.Text.Encoding]::UTF8.GetString($resp.Content)
            } else {
                $content = [string]$resp.Content
            }
            if ($content.Length -gt 0 -and $content[0] -eq [char]0xFEFF) {
                $content = $content.Substring(1)
            }

            $success = $true
            break
        } catch {
            $statusCode = $null
            try { $statusCode = [int]$_.Exception.Response.StatusCode } catch {}

            if ($statusCode -eq 429 -or $statusCode -eq 503) {
                $retryAfter = 0
                try { $retryAfter = [int]$_.Exception.Response.Headers.RetryAfter.Delta.TotalSeconds } catch {}
                if ($retryAfter -le 0) { $retryAfter = [int][math]::Min([math]::Pow(2, $i + 1), 60) }
                Start-Sleep -Seconds $retryAfter
                continue
            }

            $errMsg = "$statusCode :: $($_.Exception.Message)"
            if ($i -lt $maxRetries - 1) {
                Start-Sleep -Seconds ([int][math]::Pow(2, $i))
            } else {
                break
            }
        }
    }

    [PSCustomObject]@{
        Name    = $ep.Name
        Success = $success
        Content = $content
        Error   = $errMsg
    }
} -ThrottleLimit 3

# Report per-endpoint status
Write-Host ""
foreach ($r in $Results) {
    if ($r.Success) {
        Write-Host ("  [OK]   {0} ({1} bytes)" -f $r.Name, $r.Content.Length) -ForegroundColor Green
    } else {
        Write-Host ("  [FAIL] {0} :: {1}" -f $r.Name, $r.Error) -ForegroundColor Red
    }
}

# ------------------------------------------------------------
# Parse each response into rows
# ------------------------------------------------------------
$OneDriveData   = $null
$SharePointData = $null
$ExchangeData   = $null

foreach ($r in $Results) {
    if (-not $r.Success) { continue }
    try {
        switch ($r.Name) {
            "OneDrive"   { $OneDriveData   = $r.Content | ConvertFrom-Csv }
            "SharePoint" { $SharePointData = $r.Content | ConvertFrom-Csv }
            "Exchange"   { $ExchangeData   = $r.Content | ConvertFrom-Csv }
        }
    } catch {
        Write-Host ("Parse error for {0}: {1}" -f $r.Name, $_.Exception.Message) -ForegroundColor Red
    }
}

# ------------------------------------------------------------
# Helpers: safe [long] sum + byte formatter
# ------------------------------------------------------------
function Get-SumBytes {
    param($Data, [string]$Property, [scriptblock]$Filter = { $true })
    $total = [long]0
    if (-not $Data) { return $total }
    foreach ($row in $Data) {
        if (-not (& $Filter $row)) { continue }
        $v = $row.$Property
        if ([string]::IsNullOrWhiteSpace($v)) { continue }
        $n = [long]0
        if ([long]::TryParse($v, [ref]$n)) { $total += $n }
    }
    return $total
}

function Format-Size {
    param([long]$Bytes)
    if ($Bytes -ge 1TB) { return ("{0:N2} TB" -f ($Bytes / 1TB)) }
    if ($Bytes -ge 1GB) { return ("{0:N2} GB" -f ($Bytes / 1GB)) }
    if ($Bytes -ge 1MB) { return ("{0:N2} MB" -f ($Bytes / 1MB)) }
    if ($Bytes -ge 1KB) { return ("{0:N2} KB" -f ($Bytes / 1KB)) }
    return "$Bytes B"
}

function ConvertTo-GB {
    param([long]$Bytes)
    return [math]::Round($Bytes / 1GB, 2)
}

function Get-UsagePct {
    param([long]$Used, [long]$Total)
    if ($Total -le 0) { return "0.00%" }
    return ("{0:N2}%" -f (($Used / $Total) * 100))
}

function Format-TBUsage {
    # Formats "X.XX TB of Y.YY TB used" - forces TB unit regardless of size
    param([long]$Used, [long]$Total)
    $usedTB  = [math]::Round($Used  / 1TB, 2)
    $totalTB = [math]::Round($Total / 1TB, 2)
    return ("{0:N2} TB of {1:N2} TB used" -f $usedTB, $totalTB)
}

# Filter: exclude deleted accounts/sites/mailboxes
$ActiveFilter = { param($row) ($row.'Is Deleted' -ne 'True') -and ($row.'Is Deleted' -ne 'true') }

# ------------------------------------------------------------
# Aggregate per service
# ------------------------------------------------------------

# OneDrive
$odUsed  = Get-SumBytes -Data $OneDriveData -Property 'Storage Used (Byte)'      -Filter $ActiveFilter
$odTotal = Get-SumBytes -Data $OneDriveData -Property 'Storage Allocated (Byte)' -Filter $ActiveFilter

# SharePoint
$spUsed  = Get-SumBytes -Data $SharePointData -Property 'Storage Used (Byte)'      -Filter $ActiveFilter
$spTotal = Get-SumBytes -Data $SharePointData -Property 'Storage Allocated (Byte)' -Filter $ActiveFilter

# Exchange (Total = Prohibit Send/Receive Quota)
$exUsed  = Get-SumBytes -Data $ExchangeData -Property 'Storage Used (Byte)'                    -Filter $ActiveFilter
$exTotal = Get-SumBytes -Data $ExchangeData -Property 'Prohibit Send/Receive Quota (Byte)'     -Filter $ActiveFilter

# ------------------------------------------------------------
# Build single-row 7-column output (exact header order)
# ------------------------------------------------------------
$TotalUsed  = $odUsed  + $exUsed  + $spUsed
$TotalQuota = $odTotal + $exTotal + $spTotal

$Row = [ordered]@{
    'ONEDRIVE'           = (Format-Size -Bytes $odUsed)
    'EXCHANGE'           = (Format-Size -Bytes $exUsed)
    'SHARE POINT'        = (Format-Size -Bytes $spUsed)
    $CurrentStorageCol   = (Format-Size -Bytes $TotalUsed)
    'USAGE'              = (Format-TBUsage -Used $TotalUsed -Total $TotalQuota)
    'Used Storage(GB)'   = (ConvertTo-GB -Bytes $TotalUsed)
    'Total Storage(GB)'  = (ConvertTo-GB -Bytes $TotalQuota)
}
$Output = [PSCustomObject]$Row

# Preview (list format so long values wrap cleanly)
Write-Host ""
Write-Host "Consolidated result:" -ForegroundColor Yellow
$Output | Format-List | Out-Host

# Diagnostic counts
Write-Host "Row counts (active only):" -ForegroundColor DarkGray
Write-Host ("  OneDrive   : {0}" -f (@($OneDriveData   | Where-Object { $_.'Is Deleted' -ne 'True' }).Count)) -ForegroundColor DarkGray
Write-Host ("  SharePoint : {0}" -f (@($SharePointData | Where-Object { $_.'Is Deleted' -ne 'True' }).Count)) -ForegroundColor DarkGray
Write-Host ("  Exchange   : {0}" -f (@($ExchangeData   | Where-Object { $_.'Is Deleted' -ne 'True' }).Count)) -ForegroundColor DarkGray

# Export CSV
try {
    $Output | Export-Csv -Path $OutputPath -NoTypeInformation -Encoding UTF8
    Write-Host ""
    Write-Host "CSV exported successfully:" -ForegroundColor Green
    Write-Host "  $OutputPath" -ForegroundColor Green
} catch {
    Write-Host "ERROR: Export failed: $($_.Exception.Message)" -ForegroundColor Red
}

# Summary
$OkCount = ($Results | Where-Object Success).Count
Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host " Summary" -ForegroundColor Cyan
Write-Host "------------------------------------------------------------" -ForegroundColor Cyan
Write-Host (" Period               : {0}" -f $Period)
Write-Host (" Endpoints succeeded  : {0}/{1}" -f $OkCount, $Endpoints.Count)
Write-Host (" Output file          : {0}" -f $OutputPath)
Write-Host (" End Time             : {0}" -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'))
Write-Host "============================================================" -ForegroundColor Cyan

# Disconnect
try {
    Disconnect-MgGraph -ErrorAction Stop | Out-Null
    Write-Host "Disconnected from Microsoft Graph." -ForegroundColor DarkGray
} catch {
    Write-Host "Warning: Disconnect-MgGraph failed: $($_.Exception.Message)" -ForegroundColor Yellow
}
`
    },
    {
      id: "usage",
      title: "Usage Extraction",
      tags: "extract, usage, m365, activity, report",
      desc: "Tenant usage report via Microsoft Graph. Produces the 19 values for the Usage paste step.",
      body: `<#
.SYNOPSIS       Extract a consolidated 19-column M365 usage report (licences, activations, service activity) to CSV.
.DESCRIPTION    Read-only. Pulls four Microsoft Graph report endpoints:
                  1. getOffice365ServicesUserCounts(period='<Dxx>')  -> Active/Inactive per service
                  2. getOffice365ActivationsUserCounts               -> Assigned / Activated
                  3. getOffice365ActivationCounts                    -> Desktop / Mobile activations
                  4. subscribedSkus                                  -> Total assigned licences
                Consolidates them into a single-row, 19-column CSV. Raw endpoint responses are kept in a
                raw_<timestamp> subfolder for audit. Makes NO changes to the tenant.
                Ends with a choice to STAY SIGNED IN (default) or SIGN OUT - never forces a sign-out.

                NAVIGATION: menus accept B (back one question) and ? (redisplay). Free-text prompts accept
                :b (back). :q cancels any phase. Input phases end with an Accept / Redo / Cancel gate.
                PHASE RE-ENTRY: results live in $Global:RunState. Re-pasting one phase block re-runs only
                that phase; the Graph session and correlation ID are preserved.
.AUTHOR         Generated with Claude for Rakso CT Education IT.
.VERSION        3.0
.DATE           2026-09-30
.REQUIREMENTS   PowerShell 7+; Microsoft.Graph.Authentication.
.PERMISSIONS    Delegated: Reports.Read.All, Organization.Read.All
                Role: Reports Reader / Global Reader / Global Administrator
.SAFETY         Read-only; retry with backoff on every Graph call; correlation-ID stamped CSV + JSONL logs.
.CHANGELOG      v3.0 - Rebuilt on the current project helpers: Read-Choice (-Valid/-MenuLines), Read-Value,
                       Read-YesNo, navigation state + $Global:RunState, phase guards, Accept/Redo/Cancel
                       gates, tenant-name Y/N confirmation, Y/R/N execution gate. Phase 5 builds its own
                       timestamped file names so re-pasting Phases 4-5 never overwrites a prior run.
                       Invoke-GraphWithRetry v2 retained (see claude/Invoke-GraphWithRetry-v2.md).
                v2.2 - Sanitize-Path rule-12 [string] cast.
                v2.1 - Invoke-GraphWithRetry v2.
                v2.0 - StrictMode .Count fix, de-hardcoding, stay-signed-in choice.
                v1.0 - Initial release.
#>
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'


# ============================================================
# PHASE 0 - Helpers (paste once per terminal session)
# ============================================================
if ($PSVersionTable.PSVersion.Major -lt 7) {
    Write-Host "[FAIL] PowerShell 7+ required. Current: $($PSVersionTable.PSVersion). Open 'pwsh' and paste again." -ForegroundColor Red
    return
}

$Global:NAV_BACK = '__BACK__'
$Global:NAV_QUIT = '__QUIT__'

if (-not (Get-Variable -Name RunState -Scope Global -ErrorAction SilentlyContinue)) {
    $Global:RunState = [ordered]@{}
}

# Write-Log reads these; under StrictMode an unset global throws, so seed them once per session.
foreach ($gv in 'JsonLogFile','CorrelationId') {
    if (-not (Get-Variable -Name $gv -Scope Global -ErrorAction SilentlyContinue)) { Set-Variable -Name $gv -Scope Global -Value $null }
}

function Test-Nav {
    param($Value)
    return ($Value -is [string] -and $Value -in @($Global:NAV_BACK, $Global:NAV_QUIT))
}

function Show-NavResult {
    param([string]$Value, [string]$PhaseName)
    if ($Value -eq $Global:NAV_QUIT) {
        Write-Host "[CANCELLED] $PhaseName cancelled by operator. No changes written." -ForegroundColor Yellow
    } elseif ($Value -eq $Global:NAV_BACK) {
        Write-Host "[BACK] You are at the first question of $PhaseName." -ForegroundColor Yellow
        Write-Host "       Re-paste the PREVIOUS phase block to change an earlier answer." -ForegroundColor Yellow
        Write-Host "       Your session and all prior phase results are preserved." -ForegroundColor Yellow
    }
}

function Read-Choice {
    param(
        [Parameter(Mandatory)][string]$Prompt,
        [Parameter(Mandatory)][string[]]$Valid,
        [string]$Default,
        [string[]]$MenuLines,
        [switch]$AllowBack
    )
    $showMenu = $true
    while ($true) {
        if ($showMenu -and $MenuLines) {
            foreach ($l in $MenuLines) { Write-Host "    $l" }
            $showMenu = $false
        }
        $suffix = ''
        if ($Default)   { $suffix += " [default: $Default]" }
        if ($AllowBack) { $suffix += "  (B = back, :q = cancel)" } else { $suffix += "  (:q = cancel)" }

        $ans = (Read-Host "$Prompt$suffix").Trim()

        if ($ans -eq '?')                     { $showMenu = $true; continue }
        if ($ans -match '^(:q|quit|cancel)$') { return $Global:NAV_QUIT }
        if ($AllowBack -and $ans -match '^(b|:b|back)$') { return $Global:NAV_BACK }
        if ([string]::IsNullOrWhiteSpace($ans) -and $Default) { $ans = $Default }

        foreach ($v in $Valid) { if ($ans -ieq $v) { return $v } }

        $opts = $Valid -join ', '
        if ($AllowBack) { $opts += ', B' }
        Write-Host "[WARN] '$ans' is not a valid choice. Valid: $opts. Type ? to redisplay." -ForegroundColor Yellow
    }
}

function Read-Value {
    param(
        [Parameter(Mandatory)][string]$Prompt,
        [string]$Default,
        [switch]$Required,
        [switch]$AllowBack,
        [scriptblock]$Validator,
        [string]$ValidationMessage = 'Value failed validation.'
    )
    while ($true) {
        $suffix = ''
        if ($Default)   { $suffix += " [default: $Default]" }
        if ($AllowBack) { $suffix += "  (:b = back, :q = cancel)" } else { $suffix += "  (:q = cancel)" }

        $ans = (Read-Host "$Prompt$suffix").Trim()

        if ($ans -eq ':q')                 { return $Global:NAV_QUIT }
        if ($AllowBack -and $ans -eq ':b') { return $Global:NAV_BACK }
        if ([string]::IsNullOrWhiteSpace($ans) -and $Default) { $ans = $Default }

        if ($Required -and [string]::IsNullOrWhiteSpace($ans)) {
            Write-Host "[WARN] A value is required." -ForegroundColor Yellow; continue
        }
        if ($Validator -and -not (& $Validator $ans)) {
            Write-Host "[WARN] $ValidationMessage" -ForegroundColor Yellow; continue
        }
        return $ans
    }
}

function Read-YesNo {
    param([Parameter(Mandatory)][string]$Prompt, [string]$Default, [switch]$AllowBack)
    $r = Read-Choice -Prompt $Prompt -Valid @('Y','N') -Default $Default -AllowBack:$AllowBack
    if (Test-Nav $r) { return $r }
    return ($r -ieq 'Y')
}

function Sanitize-Path {
    param([string]$Path)
    if ([string]::IsNullOrWhiteSpace($Path)) { return '' }
    $p = $Path.Trim().Trim('"').Trim("'")
    $invisible = @([char]0x00A0,[char]0x202A,[char]0x202B,[char]0x202C,[char]0x202D,
                   [char]0x202E,[char]0x200E,[char]0x200F,[char]0xFEFF,[char]0x200B)
    # RULE 12: cast to [string] - see Sanitize-Upn note above.
    foreach ($c in $invisible) { $p = $p.Replace([string]$c, [string]'') }
    return $p
}

function Ensure-Module {
    param([Parameter(Mandatory)][string]$Name, [string]$MinVersion)

    $existing = Get-Module -ListAvailable -Name $Name |
                Sort-Object Version -Descending | Select-Object -First 1

    if ($existing) {
        if ($MinVersion -and ($existing.Version -lt [version]$MinVersion)) {
            Write-Host "[WARN] $Name $($existing.Version) is older than required $MinVersion." -ForegroundColor Yellow
            $ans = Read-YesNo -Prompt "Uninstall all versions and reinstall clean?" -Default 'N'
            if ($ans -ne $true) { return $false }
            try {
                Get-InstalledModule "$Name*" -AllVersions -ErrorAction SilentlyContinue |
                    Uninstall-Module -Force -ErrorAction SilentlyContinue
                Install-Module $Name -Scope CurrentUser -Force -AllowClobber -ErrorAction Stop
            } catch {
                Write-Host "[FAIL] Reinstall of $Name failed: $($_.Exception.Message)" -ForegroundColor Red
                return $false
            }
        }
        Import-Module $Name -ErrorAction Stop
        return $true
    }

    Write-Host "[MISSING] Module $Name is not installed." -ForegroundColor Yellow
    $ans = Read-YesNo -Prompt "Install $Name from PSGallery now?" -Default 'Y'
    if ($ans -ne $true) { return $false }
    try {
        Install-Module $Name -Scope CurrentUser -Force -AllowClobber -ErrorAction Stop
        Import-Module $Name -ErrorAction Stop
        return $true
    } catch {
        Write-Host "[FAIL] Install of $Name failed: $($_.Exception.Message)" -ForegroundColor Red
        return $false
    }
}

# Invoke-GraphWithRetry v2 (claude/Invoke-GraphWithRetry-v2.md) - supersedes the instructions' version:
# reads the typed Retry-After header and cannot throw on an uninitialised $Global:RetryCount.
function Invoke-GraphWithRetry {
    param(
        [Parameter(Mandatory)][scriptblock]$Action,
        [int]$MaxAttempts = 5,
        [int]$BaseDelaySeconds = 2,
        [int]$MaxDelaySeconds = 120
    )
    for ($i=1; $i -le $MaxAttempts; $i++) {
        try { return & $Action }
        catch {
            $err = $_; $ex = $err.Exception
            $status = $null; $retryAfter = $null

            # StrictMode-safe: probe before touching. Not every Graph exception exposes .Response.
            $resp = $null
            if ($ex -and $ex.PSObject.Properties['Response']) { $resp = $ex.Response }
            if ($resp) {
                try { $status = [int]$resp.StatusCode } catch { }
                # HttpResponseMessage: typed RetryAfter (delta-seconds or HTTP-date). It has no string indexer.
                try {
                    $ra = $resp.Headers.RetryAfter
                    if ($ra -and $ra.Delta) { $retryAfter = [int][Math]::Ceiling($ra.Delta.TotalSeconds) } elseif ($ra -and $ra.Date) { $retryAfter = [int][Math]::Ceiling(($ra.Date - [DateTimeOffset]::UtcNow).TotalSeconds) }
                } catch { }
                # Dictionary-shaped headers (other exception types)
                if ($null -eq $retryAfter) {
                    try { $v = $resp.Headers['Retry-After']; if ($v) { $retryAfter = [int](@($v)[0]) } } catch { }
                }
            }
            # Graph SDK does not always expose .Response - fall back to the message text.
            # $err.ErrorDetails is often $null; under StrictMode $null.Message throws, so guard it.
            if ($null -eq $status) {
                $detail = ''
                if ($err.ErrorDetails) { $detail = [string]$err.ErrorDetails.Message }
                $msg = [string]$ex.Message
                if ($detail -match 'TooManyRequests|throttl' -or $msg -match '\\b429\\b|Too ?Many ?Requests') { $status = 429 } elseif ($msg -match '\\b(500|502|503|504)\\b') { $status = [int]$Matches[1] } elseif ($msg -match 'Service Unavailable|Gateway Time-?out|Bad Gateway') { $status = 503 }
            }

            $isRetryable = $status -in 429,500,502,503,504
            if (-not $isRetryable -or $i -eq $MaxAttempts) { throw $err }

            $delay = if ($retryAfter -and $retryAfter -gt 0) { $retryAfter } else { [int][Math]::Pow($BaseDelaySeconds, $i) }
            $delay = [Math]::Min([Math]::Max($delay, 1), $MaxDelaySeconds)
            Write-Host "[RETRY $i/$MaxAttempts] HTTP $status, sleeping \${delay}s..." -ForegroundColor DarkYellow
            Start-Sleep -Seconds $delay
            # StrictMode-safe counter: works even if $Global:RetryCount was never initialised
            $Global:RetryCount = [int](Get-Variable -Name RetryCount -Scope Global -ValueOnly -ErrorAction SilentlyContinue) + 1
        }
    }
}

function Write-Log {
    param(
        [string]$Message,
        [ValidateSet('INFO','WARN','ERROR','SUCCESS','AUDIT','SECURITY')][string]$Level='INFO'
    )
    $ts = Get-Date -Format 'yyyy-MM-dd HH:mm:ss.fff'
    $line = "$ts [$Level] [$Global:CorrelationId] $Message"
    $color = @{INFO='Gray';WARN='Yellow';ERROR='Red';SUCCESS='Green';AUDIT='Cyan';SECURITY='Magenta'}[$Level]
    Write-Host $line -ForegroundColor $color
    if ($Global:JsonLogFile) {
        $obj = [ordered]@{ ts=$ts; level=$Level; correlationId=$Global:CorrelationId; message=$Message }
        ($obj | ConvertTo-Json -Compress) | Add-Content -LiteralPath $Global:JsonLogFile -Encoding UTF8
    }
}

# --- Script-specific helpers ---

# Int value of the first matching column on a row, or $null if no such column (StrictMode-safe).
function Get-ColInt {
    param([object]$Row, [string[]]$Names)
    if ($null -eq $Row) { return $null }
    $col = @($Row.PSObject.Properties.Name) | Where-Object { $_ -in $Names } | Select-Object -First 1
    if (-not $col) { return $null }
    $v = 0; [void][int]::TryParse([string]$Row.$col, [ref]$v)
    return $v
}

# Sum of the first matching column across rows, or $null if no such column (StrictMode-safe).
function Get-ColSum {
    param([object[]]$Rows, [string[]]$Names)
    $list = @($Rows)
    if ($list.Count -eq 0) { return $null }
    $col = @($list[0].PSObject.Properties.Name) | Where-Object { $_ -in $Names } | Select-Object -First 1
    if (-not $col) { return $null }
    $sum = 0
    foreach ($r in $list) { $v = 0; if ([int]::TryParse([string]$r.$col, [ref]$v)) { $sum += $v } }
    return $sum
}

# Stay signed in (default) or sign out. Never forces a sign-out. :q keeps the session.
function Invoke-SessionChoice {
    $ctx = Get-MgContext -ErrorAction SilentlyContinue
    if (-not $ctx) { return }
    Write-Host ''
    Write-Host '=== SESSION ===' -ForegroundColor Cyan
    $r = Read-Choice -Prompt 'Session' -Valid @('1','2') -Default '1' -MenuLines @(
        "[1] Stay signed in as $($ctx.Account)  (next run: sign-in mode [3] Reuse)",
        '[2] Sign out now (Disconnect-MgGraph)')
    if ($r -eq '2') {
        try {
            Disconnect-MgGraph -ErrorAction Stop | Out-Null
            Write-Log 'Signed out of Microsoft Graph.' 'AUDIT'
        } catch {
            Write-Log "Disconnect-MgGraph failed: $($_.Exception.Message)" 'WARN'
        }
    } else {
        Write-Log "Session kept for $($ctx.Account). Sign out any time with: Disconnect-MgGraph" 'INFO'
    }
}

Write-Host '>>> Phase 0 complete. Keys: B = back (menus) | :b = back (text) | :q = cancel | ? = redisplay' -ForegroundColor Green


# ============================================================
# PHASE 1 - Configure Paths + Period
# ============================================================
Write-Host ''
Write-Host '=== PHASE 1: Configure Paths + Period ===' -ForegroundColor Cyan

$Global:ScriptName = 'Bulk-ExtractM365UsageReport'
$DocsRoot          = [Environment]::GetFolderPath('MyDocuments')
if ([string]::IsNullOrWhiteSpace($DocsRoot)) { $DocsRoot = $HOME }   # redirected/empty Documents
$DefaultOutFolder  = Join-Path $DocsRoot 'M365-Reports\\UsageReport\\Logs'

if (-not $Global:RunState.Contains('CorrelationId')) {
    $Global:RunState['CorrelationId'] = [guid]::NewGuid().ToString('N').Substring(0,12)
}
$Global:CorrelationId = $Global:RunState['CorrelationId']

$phaseDone = $false
while (-not $phaseDone) {
    $cancelled = $false
    $folder = $null; $period = $null
    $sub = 1
    while ($sub -le 2) {
        if ($sub -eq 1) {
            $defFolder = if ($Global:RunState.Contains('Phase1')) { $Global:RunState['Phase1'].OutputFolder } else { $DefaultOutFolder }
            $raw = Read-Value -Prompt 'Output log folder' -Default $defFolder -Required
            if ($raw -eq $Global:NAV_QUIT) { $cancelled = $true; break }

            $clean = Sanitize-Path $raw
            $stripped = @($raw.ToCharArray() | Where-Object { [int]$_ -gt 127 -or [char]::IsControl($_) } |
                          ForEach-Object { 'U+{0:X4}' -f [int]$_ })
            if ($stripped.Count -gt 0) {
                Write-Host "[WARN] Stripped invisible chars: $($stripped -join ' ')" -ForegroundColor Yellow
                Write-Host "       Cleaned path: $clean" -ForegroundColor Yellow
            }
            if ([string]::IsNullOrWhiteSpace($clean)) { Write-Host '[WARN] Path is empty after cleaning.' -ForegroundColor Yellow; continue }

            if (-not (Test-Path -LiteralPath $clean)) {
                $mk = Read-YesNo -Prompt "Folder does not exist. Create '$clean'?" -Default 'Y' -AllowBack
                if ($mk -is [string] -and $mk -eq $Global:NAV_QUIT) { $cancelled = $true; break }
                if ($mk -ne $true) { continue }   # N or B -> re-ask the folder
                try {
                    New-Item -Path $clean -ItemType Directory -Force | Out-Null
                    Write-Host "[OK] Created folder: $clean" -ForegroundColor Green
                } catch {
                    Write-Host "[FAIL] Cannot create folder '$clean': $($_.Exception.Message)" -ForegroundColor Red
                    continue
                }
            }
            $folder = $clean
            $sub = 2
        } else {
            $defPeriod = if ($Global:RunState.Contains('Phase1')) { $Global:RunState['Phase1'].Period } else { 'D30' }
            $period = Read-Choice -Prompt 'Report period for service activity' -Valid @('D7','D30','D90','D180')  -Default $defPeriod -AllowBack -MenuLines @(
                        '[D7]   last 7 days', '[D30]  last 30 days', '[D90]  last 90 days', '[D180] last 180 days')
            if ($period -eq $Global:NAV_BACK) { $sub = 1; continue }
            if ($period -eq $Global:NAV_QUIT) { $cancelled = $true; break }
            $sub = 3
        }
    }
    if ($cancelled) { Show-NavResult $Global:NAV_QUIT 'Phase 1'; break }

    Write-Host ''
    Write-Host "  Correlation ID : $Global:CorrelationId" -ForegroundColor Green
    Write-Host "  Output folder  : $folder"               -ForegroundColor Green
    Write-Host "  Period         : $period"               -ForegroundColor Green
    Write-Host "  Files          : M365_UsageReport_\${period}_<timestamp>.csv + run log .csv/.jsonl (named at Phase 5)" -ForegroundColor Green

    $accept = Read-Choice -Prompt 'Accept?' -Valid @('A','R','Q') -Default 'A' -MenuLines @(
        '[A] Accept and continue', '[R] Redo this phase', '[Q] Cancel')
    if ($accept -eq 'R') { continue }
    if ($accept -ne 'A') { Show-NavResult $Global:NAV_QUIT 'Phase 1'; break }

    $Global:RunState['Phase1'] = [pscustomobject]@{ OutputFolder = $folder; Period = $period }
    $phaseDone = $true
}
if (-not $phaseDone) { return }
Write-Host '>>> Phase 1 complete. Re-run this phase any time by pasting the Phase 1 block again.' -ForegroundColor Green


# ============================================================
# PHASE 2 - Connect to Microsoft Graph + Confirm Tenant
# ============================================================
Write-Host ''
Write-Host '=== PHASE 2: Connect to Microsoft Graph ===' -ForegroundColor Cyan

if (-not $Global:RunState.Contains('Phase1')) { Write-Host '[FAIL] Phase 1 is not complete. Re-paste Phase 1.' -ForegroundColor Red; return }
if (-not (Ensure-Module -Name 'Microsoft.Graph.Authentication')) {
    Write-Host '[FAIL] Microsoft.Graph.Authentication unavailable. Install it, then re-paste Phase 2.' -ForegroundColor Red
    return
}

$Global:RequiredScopes = @('Reports.Read.All','Organization.Read.All')
$phaseDone = $false; $cancelled = $false
$tenantId = $null; $mode = '1'; $ctx = $null; $tenantName = $null; $missing = @()
$sub = 1
while (-not $phaseDone -and -not $cancelled) {
    if ($sub -eq 1) {
        $existing = Get-MgContext -ErrorAction SilentlyContinue
        $defTenant = if ($Global:RunState.Contains('Phase2')) { $Global:RunState['Phase2'].TenantId } elseif ($existing) { [string]$existing.TenantId } else { '' }
        $t = Read-Value -Prompt 'Tenant ID (GUID)' -Default $defTenant -Required -AllowBack  -Validator { param($v) $g = [guid]::Empty; [guid]::TryParse((Sanitize-Path $v), [ref]$g) }  -ValidationMessage 'Not a valid GUID (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).'
        if (Test-Nav $t) { Show-NavResult $t 'Phase 2'; $cancelled = $true; continue }
        $tenantId = (Sanitize-Path $t).ToLowerInvariant()
        $sub = 2
    } elseif ($sub -eq 2) {
        $mode = Read-Choice -Prompt 'Sign-in mode' -Valid @('1','2','3') -Default '1' -AllowBack -MenuLines @(
            '[1] Browser session / DeviceCode flow (default)', '[2] Interactive popup', '[3] Reuse existing session')
        if ($mode -eq $Global:NAV_BACK) { $sub = 1; continue }
        if ($mode -eq $Global:NAV_QUIT) { Show-NavResult $mode 'Phase 2'; $cancelled = $true; continue }
        $sub = 3
    } elseif ($sub -eq 3) {
        Write-Host "Scopes requested: $($Global:RequiredScopes -join ', ')" -ForegroundColor Gray
        try {
            $needConnect = $true
            if ($mode -eq '3') {
                $c = Get-MgContext -ErrorAction SilentlyContinue
                $gap = if ($c) { @($Global:RequiredScopes | Where-Object { $_ -notin @($c.Scopes) }) } else { @('n/a') }
                if ($c -and ([string]$c.TenantId -eq $tenantId) -and $gap.Count -eq 0) {
                    $needConnect = $false
                    Write-Host "[OK] Reusing existing session: $($c.Account)" -ForegroundColor Green
                } else {
                    Write-Host '[WARN] No reusable session (none / different tenant / missing scopes). Using DeviceCode.' -ForegroundColor Yellow
                    $mode = '1'
                }
            }
            if ($needConnect) {
                $p = @{ TenantId = $tenantId; Scopes = $Global:RequiredScopes; NoWelcome = $true; ErrorAction = 'Stop' }
                if ($mode -eq '1') { $p.UseDeviceCode = $true }
                Write-Host ("Connecting via {0}..." -f @{ '1'='DeviceCode'; '2'='Interactive' }[$mode]) -ForegroundColor Cyan
                Connect-MgGraph @p
            }
        } catch {
            Write-Host "[FAIL] Connect failed: $($_.Exception.Message)" -ForegroundColor Red
            Write-Host '       Pick a different sign-in mode, or B to change the Tenant ID.' -ForegroundColor Yellow
            $sub = 2; continue
        }

        $ctx = Get-MgContext
        if (-not $ctx -or [string]::IsNullOrWhiteSpace([string]$ctx.Account)) {
            Write-Host '[FAIL] No Graph context/account after sign-in. Re-enter Tenant ID.' -ForegroundColor Red
            $sub = 1; continue
        }
        if ([string]$ctx.TenantId -ne $tenantId) {
            Write-Host "[FAIL] Signed-in tenant ($($ctx.TenantId)) does not match requested ($tenantId)." -ForegroundColor Red
            $sub = 1; continue
        }
        try {
            $org = Invoke-GraphWithRetry -Action {
                Invoke-MgGraphRequest -Method GET -Uri 'https://graph.microsoft.com/v1.0/organization?$select=displayName' -OutputType PSObject -ErrorAction Stop
            }
            $tenantName = @($org.value)[0].displayName
        } catch {
            $tenantName = '(unresolved - Organization.Read.All may be missing)'
        }
        $sub = 4
    } elseif ($sub -eq 4) {
        Write-Host ''
        Write-Host "  Tenant  : $tenantName ($($ctx.TenantId))" -ForegroundColor Cyan
        Write-Host "  Account : $($ctx.Account)"                -ForegroundColor Cyan
        $ok = Read-YesNo -Prompt 'Is this the correct tenant?' -AllowBack
        if ($ok -is [string] -and $ok -eq $Global:NAV_QUIT) { Show-NavResult $ok 'Phase 2'; $cancelled = $true; continue }
        if ($ok -is [string] -and $ok -eq $Global:NAV_BACK) { $sub = 2; continue }
        if ($ok -ne $true) {
            # Wrong tenant: the one place a sign-out is forced, so nothing is read from it.
            Disconnect-MgGraph -ErrorAction SilentlyContinue | Out-Null
            if ($Global:RunState.Contains('Phase2')) { $Global:RunState.Remove('Phase2') }
            Write-Host '[OK] Signed out of the wrong tenant. Enter the correct Tenant ID.' -ForegroundColor Yellow
            $sub = 1; continue
        }
        $sub = 5
    } else {
        # @() forces an array so .Count works under StrictMode when 0 or 1 scope is missing
        $missing = @($Global:RequiredScopes | Where-Object { $_ -notin @($ctx.Scopes) })
        if ($missing.Count -eq 0) { Write-Host '[OK] All required scopes granted.' -ForegroundColor Green; $phaseDone = $true; continue }

        Write-Host "[WARN] Missing scopes: $($missing -join ', ')" -ForegroundColor Yellow
        $fix = Read-Choice -Prompt 'Choose' -Valid @('R','C') -AllowBack -MenuLines @(
            '[R] Reconnect and consent to missing scopes (Interactive popup)',
            '[C] Continue anyway (affected reports will FAIL)',
            '[B] Back to Tenant ID')
        if ($fix -eq $Global:NAV_BACK) { $sub = 1; continue }
        if ($fix -eq $Global:NAV_QUIT) { Show-NavResult $fix 'Phase 2'; $cancelled = $true; continue }
        if ($fix -eq 'R') { $mode = '2'; $sub = 3; continue }
        $phaseDone = $true
    }
}
if (-not $phaseDone) { Invoke-SessionChoice; return }

$Global:RunState['Phase2'] = [pscustomobject]@{
    TenantId = [string]$ctx.TenantId; TenantName = $tenantName; Account = [string]$ctx.Account; MissingScopes = $missing
}
Write-Log "Connected: tenant=$($ctx.TenantId) ($tenantName) account=$($ctx.Account)" 'AUDIT'
Write-Host '>>> Phase 2 complete. Re-run this phase any time by pasting the Phase 2 block again.' -ForegroundColor Green


# ============================================================
# PHASE 3 - Preview Endpoints
# ============================================================
Write-Host ''
Write-Host '=== PHASE 3: Preview Endpoints ===' -ForegroundColor Cyan

if (-not $Global:RunState.Contains('Phase2')) { Write-Host '[FAIL] Phase 2 is not complete. Re-paste Phase 2.' -ForegroundColor Red; return }
$Period = $Global:RunState['Phase1'].Period

$Endpoints = @(
    [pscustomobject]@{ Name='Services';      Type='csv';  Uri="https://graph.microsoft.com/v1.0/reports/getOffice365ServicesUserCounts(period='$Period')" }
    [pscustomobject]@{ Name='Activations';   Type='csv';  Uri='https://graph.microsoft.com/v1.0/reports/getOffice365ActivationsUserCounts' }
    [pscustomobject]@{ Name='ActivationDev'; Type='csv';  Uri='https://graph.microsoft.com/v1.0/reports/getOffice365ActivationCounts' }
    [pscustomobject]@{ Name='Skus';          Type='json'; Uri='https://graph.microsoft.com/v1.0/subscribedSkus' }
)

$phaseDone = $false
while (-not $phaseDone) {
    $Endpoints | Format-Table Name, Type, Uri -AutoSize | Out-Host
    $missing = @($Global:RunState['Phase2'].MissingScopes)
    if ($missing.Count -gt 0) { Write-Host "[WARN] Missing scopes: $($missing -join ', ') - expect FAIL on affected endpoints." -ForegroundColor Yellow }
    $accept = Read-Choice -Prompt 'Accept?' -Valid @('A','R','Q') -Default 'A' -MenuLines @(
        '[A] Accept and continue', '[R] Redisplay', '[Q] Cancel')
    if ($accept -eq 'R') { continue }
    if ($accept -ne 'A') { Show-NavResult $Global:NAV_QUIT 'Phase 3'; break }
    $Global:RunState['Phase3'] = $Endpoints
    $phaseDone = $true
}
if (-not $phaseDone) { Invoke-SessionChoice; return }
Write-Host '>>> Phase 3 complete. Re-run this phase any time by pasting the Phase 3 block again.' -ForegroundColor Green


# ============================================================
# PHASE 4 - Confirmation
# ============================================================
Write-Host ''
Write-Host '=== PHASE 4: Confirmation ===' -ForegroundColor Cyan

if (-not $Global:RunState.Contains('Phase3')) { Write-Host '[FAIL] Phase 3 is not complete. Re-paste Phase 3.' -ForegroundColor Red; return }
if ($Global:RunState.Contains('Phase4')) { $Global:RunState.Remove('Phase4') }

$confirmed = $false
while ($true) {
    $p1 = $Global:RunState['Phase1']; $p2 = $Global:RunState['Phase2']
    Write-Host ''
    Write-Host "About to READ $(@($Global:RunState['Phase3']).Count) report endpoints. No tenant changes." -ForegroundColor Yellow
    Write-Host "  Tenant  : $($p2.TenantName) ($($p2.TenantId))"
    Write-Host "  Account : $($p2.Account)"
    Write-Host "  Period  : $($p1.Period)"
    Write-Host "  Folder  : $($p1.OutputFolder)"
    $go = Read-Choice -Prompt 'Execute?' -Valid @('Y','R','N') -MenuLines @(
        '[Y] Execute (read-only pull)',
        '[R] Redisplay (to change answers, re-paste Phase 1, 2 or 3)',
        '[N] Cancel')
    if ($go -eq 'R') { continue }
    if ($go -eq 'Y') { $confirmed = $true }
    break
}
if (-not $confirmed) {
    Write-Host '[CANCELLED] Nothing was pulled.' -ForegroundColor Yellow
    Invoke-SessionChoice
    return
}
$Global:RunState['Phase4'] = [pscustomobject]@{ Confirmed = $true; At = (Get-Date -Format 'o') }
Write-Host '>>> Phase 4 complete.' -ForegroundColor Green


# ============================================================
# PHASE 5 - Pull + Consolidate + Export
# ============================================================
Write-Host ''
Write-Host '=== PHASE 5: Pull Reports + Export ===' -ForegroundColor Cyan

if (-not $Global:RunState.Contains('Phase4')) { Write-Host '[FAIL] Phase 4 was not confirmed. Re-paste Phase 4.' -ForegroundColor Red; return }

# Fresh file names per run, so re-pasting Phases 4-5 never overwrites a prior run
if (-not $Global:RunState.Contains('CorrelationId')) {
    $Global:RunState['CorrelationId'] = [guid]::NewGuid().ToString('N').Substring(0,12)
}
$Global:CorrelationId = $Global:RunState['CorrelationId']
$Period      = $Global:RunState['Phase1'].Period
$OutFolder   = $Global:RunState['Phase1'].OutputFolder
$Endpoints   = @($Global:RunState['Phase3'])
$TimeStamp   = Get-Date -Format 'yyyyMMdd_HHmmss'
$OutputPath  = Join-Path $OutFolder "M365_UsageReport_\${Period}_$TimeStamp.csv"
$LogFile     = Join-Path $OutFolder "$($Global:ScriptName)_$TimeStamp.csv"
$FailedFile  = Join-Path $OutFolder "$($Global:ScriptName)_\${TimeStamp}_FAILED.csv"
$RawFolder   = Join-Path $OutFolder "raw_$TimeStamp"
$Global:JsonLogFile = Join-Path $OutFolder "$($Global:ScriptName)_$TimeStamp.jsonl"
$Global:RetryCount  = 0

$sw     = [Diagnostics.Stopwatch]::StartNew()
$RunLog = [System.Collections.Generic.List[object]]::new()
$Data   = @{}
New-Item -Path $RawFolder -ItemType Directory -Force | Out-Null
Write-Log "Run started. Endpoints=$($Endpoints.Count) Period=$Period Tenant=$($Global:RunState['Phase2'].TenantId)" 'AUDIT'

$n = 0; $ok = 0; $fail = 0
foreach ($ep in $Endpoints) {
    $n++
    $retryBefore = $Global:RetryCount
    $row = [ordered]@{
        CorrelationId = $Global:CorrelationId; Timestamp = (Get-Date -Format 'o')
        Endpoint = $ep.Name; Type = $ep.Type; Uri = $ep.Uri
        Status = ''; Retries = 0; RowsReturned = 0; RawFile = ''; ErrorCode = ''; ErrorMessage = ''
    }
    try {
        if ($ep.Type -eq 'csv') {
            $rawFile = Join-Path $RawFolder "$($ep.Name).csv"
            Invoke-GraphWithRetry -Action {
                Invoke-MgGraphRequest -Method GET -Uri $ep.Uri -OutputFilePath $rawFile -ErrorAction Stop
            } | Out-Null
            $rows = @(Import-Csv -LiteralPath $rawFile -Encoding UTF8)
        } else {
            $rawFile = Join-Path $RawFolder "$($ep.Name).json"
            $resp = Invoke-GraphWithRetry -Action {
                Invoke-MgGraphRequest -Method GET -Uri $ep.Uri -OutputType PSObject -ErrorAction Stop
            }
            $resp | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath $rawFile -Encoding UTF8
            $rows = @($resp.value)
        }
        $Data[$ep.Name] = $rows
        $row.Status = 'OK'; $row.RowsReturned = $rows.Count; $row.RawFile = $rawFile
        $ok++
        Write-Host ("  [OK]   {0}  ({1} rows)" -f $ep.Name, $rows.Count) -ForegroundColor Green
    } catch {
        $err  = $_
        $code = ''
        try {
            if ($err.Exception.PSObject.Properties['Response'] -and $err.Exception.Response) {
                $code = [int]$err.Exception.Response.StatusCode
            }
        } catch {}
        $row.Status = 'FAIL'; $row.ErrorCode = $code; $row.ErrorMessage = $err.Exception.Message
        $fail++
        Write-Host ("  [FAIL] {0} :: {1} {2}" -f $ep.Name, $code, $err.Exception.Message) -ForegroundColor Red
        Write-Log "Endpoint $($ep.Name) failed: $code $($err.Exception.Message)" 'ERROR'
    }
    $row.Retries = $Global:RetryCount - $retryBefore
    $RunLog.Add([pscustomobject]$row)
    if ($n % 25 -eq 0) { Write-Host "[HEARTBEAT] Endpoint $n/$($Endpoints.Count) - OK $ok / FAIL $fail" -ForegroundColor DarkCyan }
}

# --- Extract (every lookup StrictMode-safe) ---
$Services      = @(if ($Data.ContainsKey('Services'))      { $Data['Services'] })
$Activations   = @(if ($Data.ContainsKey('Activations'))   { $Data['Activations'] })
$ActivationDev = @(if ($Data.ContainsKey('ActivationDev')) { $Data['ActivationDev'] })
$Skus          = @(if ($Data.ContainsKey('Skus'))          { $Data['Skus'] })

$TotalAssignedLicenses = 0
foreach ($s in $Skus) { if ($s.PSObject.Properties['consumedUnits']) { $TotalAssignedLicenses += [int]$s.consumedUnits } }

$TotalActivated = (Get-ColSum -Rows $Activations -Names 'Activated') ?? 0

$win = (Get-ColSum -Rows $ActivationDev -Names 'Windows')           ?? 0
$mac = (Get-ColSum -Rows $ActivationDev -Names 'Mac')               ?? 0
$and = (Get-ColSum -Rows $ActivationDev -Names 'Android')           ?? 0
$ios = (Get-ColSum -Rows $ActivationDev -Names 'iOS')               ?? 0
$wp  = (Get-ColSum -Rows $ActivationDev -Names 'Windows 10 Mobile') ?? 0
$DesktopApps = [int]($win + $mac)
$MobileApps  = [int]($and + $ios + $wp)

$latest = $Services |
    Where-Object { $_.PSObject.Properties['Report Refresh Date'] -and $_.'Report Refresh Date' } |
    Sort-Object { [datetime]$_.'Report Refresh Date' } -Descending |
    Select-Object -First 1
if (-not $latest -and $Services.Count -gt 0) { $latest = $Services[0] }

$ExActive   = (Get-ColInt $latest 'Exchange Active')     ?? 0
$ExInactive = (Get-ColInt $latest 'Exchange Inactive')   ?? 0
$ODActive   = (Get-ColInt $latest 'OneDrive Active')     ?? 0
$ODInactive = (Get-ColInt $latest 'OneDrive Inactive')   ?? 0
$SPActive   = (Get-ColInt $latest 'SharePoint Active')   ?? 0
$SPInactive = (Get-ColInt $latest 'SharePoint Inactive') ?? 0
$TmActive   = (Get-ColInt $latest 'Teams Active')        ?? 0
$TmInactive = (Get-ColInt $latest 'Teams Inactive')      ?? 0

# M365 Apps (portal name) = "Office 365" (Graph legacy name); accept both
$M365AppsActive   = (Get-ColInt $latest @('Microsoft 365 Apps Active','Office 365 Active')) ?? 0
$M365AppsInactive =  Get-ColInt $latest @('Microsoft 365 Apps Inactive','Office 365 Inactive')
if ($null -eq $M365AppsInactive) {
    $M365AppsInactive = [math]::Max(0, $TotalAssignedLicenses - $M365AppsActive)
    if ($latest) { Write-Log 'M365 Apps Inactive not in report; derived as (Total Licences - Active).' 'WARN' }
}

$Output = [pscustomobject][ordered]@{
    'Total Number of Assigned Licenses' = $TotalAssignedLicenses
    'Activated'                         = $TotalActivated
    'Desktop Apps'                      = $DesktopApps
    'Mobile Apps'                       = $MobileApps
    'Exchange Active'                   = $ExActive
    'Exchange Inactive'                 = $ExInactive
    'Total of Exchange Users'           = ($ExActive + $ExInactive)
    'OneDrive Active'                   = $ODActive
    'OneDrive Inactive'                 = $ODInactive
    'Total of OneDrive Users'           = ($ODActive + $ODInactive)
    'SharePoint Active'                 = $SPActive
    'SharePoint Inactive'               = $SPInactive
    'Total of SharePoint Users'         = ($SPActive + $SPInactive)
    'Teams Active'                      = $TmActive
    'Teams Inactive'                    = $TmInactive
    'Total of Teams Users'              = ($TmActive + $TmInactive)
    'Microsoft 365 Apps Active'         = $M365AppsActive
    'Microsoft 365 Apps Inactive'       = $M365AppsInactive
    'Total of Microsoft 365 Apps Users' = ($M365AppsActive + $M365AppsInactive)
}
Write-Host ''
Write-Host 'Consolidated result:' -ForegroundColor Yellow
$Output | Format-List | Out-Host

try {
    $Output | Export-Csv -LiteralPath $OutputPath -NoTypeInformation -Encoding UTF8
    Write-Log "Report exported: $OutputPath" 'SUCCESS'
} catch {
    Write-Log "Report export failed: $($_.Exception.Message)" 'ERROR'
}
$RunLog | Export-Csv -LiteralPath $LogFile -NoTypeInformation -Encoding UTF8
$FailedRows = @($RunLog | Where-Object { $_.Status -eq 'FAIL' })
if ($FailedRows.Count -gt 0) { $FailedRows | Export-Csv -LiteralPath $FailedFile -NoTypeInformation -Encoding UTF8 }

$sw.Stop()
Write-Host ''
Write-Host '=== EXECUTION SUMMARY ===' -ForegroundColor Cyan
Write-Host ("Correlation ID  : {0}" -f $Global:CorrelationId)
Write-Host ("Total endpoints : {0}" -f $Endpoints.Count)
Write-Host ("Succeeded       : {0}" -f $ok)
Write-Host ("Failed          : {0}" -f $fail)
Write-Host  "Skipped         : 0   (read-only; n/a)"
Write-Host ("Retried         : {0}" -f $Global:RetryCount)
Write-Host ("Duration        : {0}" -f $sw.Elapsed.ToString('hh\\:mm\\:ss'))
Write-Host ("Log file        : {0}" -f $LogFile)
Write-Host ("Report CSV      : {0}" -f $OutputPath)
Write-Host ("Raw responses   : {0}" -f $RawFolder)
if ($FailedRows.Count -gt 0) {
    Write-Host ("Failed CSV      : {0}" -f $FailedFile) -ForegroundColor Red
    Write-Host  "Re-run          : fix scopes/role, then paste Phases 4 and 5 again" -ForegroundColor Yellow
}
Write-Host '=========================' -ForegroundColor Cyan
Write-Log "Run finished. OK=$ok FAIL=$fail RETRIED=$($Global:RetryCount)" 'AUDIT'

# Close out this run: next Phase 4+5 paste gets a fresh correlation ID and needs re-confirmation
$Global:RunState.Remove('CorrelationId')
$Global:RunState.Remove('Phase4')

Invoke-SessionChoice
Write-Host '>>> Phase 5 complete. To pull again with the same settings, paste Phases 4 and 5 again.' -ForegroundColor Green`
    }
  ];

  /* Tenant pre-fill: verbatim anchor line -> replacement carrying the tenant ID. */
  var PREFILL = {
    storage: {
      from: '$InputTenantId = Read-Host "Enter Tenant ID (GUID)"',
      to: function (id) { return '$InputTenantId = "' + id + '"  # pre-filled by QBR dashboard'; }
    },
    usage: {
      from: "$t = Read-Value -Prompt 'Tenant ID (GUID)' -Default $defTenant -Required -AllowBack",
      to: function (id) { return "$t = Read-Value -Prompt 'Tenant ID (GUID)' -Default \"" + id + "\" -Required -AllowBack  # pre-filled by QBR dashboard"; }
    }
  };

  function loadCustom() {
    try {
      var a = JSON.parse(localStorage.getItem(LS_KEY) || "[]");
      return Array.isArray(a) ? a : [];
    } catch (e) { return []; }
  }
  function saveCustom(list) {
    try { localStorage.setItem(LS_KEY, JSON.stringify(list)); } catch (e) { /* storage full/blocked */ }
  }
  function cleanRec(r) {
    return { id: String(r.id), title: String(r.title), tags: String(r.tags || ""), desc: String(r.desc || ""), body: String(r.body) };
  }

  function scriptList() {
    var map = {};
    BUILTINS.forEach(function (s) { map[s.id] = { id: s.id, title: s.title, tags: s.tags, desc: s.desc, body: s.body, builtin: true }; });
    loadCustom().forEach(function (r) {
      if (r && r.id && r.title && r.body) map[r.id] = { id: r.id, title: r.title, tags: r.tags || "", desc: r.desc || "", body: r.body, builtin: false };
    });
    return Object.keys(map).map(function (k) { return map[k]; });
  }
  function scriptGet(id) {
    var found = null;
    scriptList().forEach(function (s) { if (s.id === id) found = s; });
    return found;
  }
  function scriptUpsert(rec) {
    if (!rec || !rec.id || !rec.title || !rec.body) throw new Error("id, title and body are required.");
    var list = loadCustom().filter(function (s) { return s.id !== rec.id; });
    list.push(cleanRec(rec));
    saveCustom(list);
  }
  function scriptDelete(id) {
    saveCustom(loadCustom().filter(function (s) { return s.id !== id; }));
  }
  function scriptSearch(q) {
    q = (q || "").toLowerCase().trim();
    if (!q) return scriptList();
    return scriptList().filter(function (s) {
      return (s.title + " " + s.tags + " " + s.desc).toLowerCase().indexOf(q) >= 0;
    });
  }
  function scriptExport() { return JSON.stringify(loadCustom(), null, 2); }
  function scriptImport(text) {
    var arr = JSON.parse(text);
    if (!Array.isArray(arr)) throw new Error("Import file must contain a JSON array.");
    var clean = arr.map(function (r, i) {
      if (!r || !r.title || !r.body) throw new Error("Entry " + (i + 1) + " is missing a title or body.");
      return cleanRec({ id: r.id || ("imported-" + Date.now() + "-" + i), title: r.title, tags: r.tags, desc: r.desc, body: r.body });
    });
    saveCustom(clean);
    return clean.length;
  }

  /* Build the copyable text for a script, pre-filling the tenant ID when known.
     Returns { text, prefilled, title } or null for an unknown script id. */
  function scriptCopyText(id, tenantId) {
    var s = scriptGet(id);
    if (!s) return null;
    var text = s.body, prefilled = false;
    var p = PREFILL[id];
    if (tenantId && p && text.indexOf(p.from) >= 0) {
      text = text.replace(p.from, p.to(tenantId));
      prefilled = true;
    }
    return { text: text, prefilled: prefilled, title: s.title };
  }

  function copyToClipboard(text) {
    function fallback() {
      var ta = document.createElement("textarea");
      ta.value = text;
      ta.style.position = "fixed"; ta.style.opacity = "0";
      document.body.appendChild(ta); ta.select();
      var ok = false;
      try { ok = document.execCommand("copy"); } catch (e) {}
      document.body.removeChild(ta);
      return ok;
    }
    if (navigator.clipboard && navigator.clipboard.writeText) {
      return navigator.clipboard.writeText(text).then(function () { return true; }, function () { return fallback(); });
    }
    return Promise.resolve(fallback());
  }

  /* ------------------------------------------------------------------ */
  /* Scripts overlay UI (opened from the wizard's "Manage scripts").      */
  /* ------------------------------------------------------------------ */
  function escHtml(s) {
    return String(s == null ? "" : s).replace(/[&<>"']/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c];
    });
  }

  var overlay = null;
  var editingId = null;
  var cssDone = false;

  var CSS = [
    ".qbr-scripts-overlay{position:fixed;inset:0;background:rgba(0,0,0,.45);z-index:2000;display:flex;align-items:flex-start;justify-content:center;padding:36px 14px;overflow:auto}",
    ".qbr-scripts-modal{background:#fff;color:#222;border-radius:8px;max-width:880px;width:100%;padding:20px 22px;box-shadow:0 8px 30px rgba(0,0,0,.25)}",
    ".qbr-scripts-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px}",
    ".qbr-scripts-head h3{margin:0;font-size:19px}",
    ".qbr-scripts-toolbar{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:14px;align-items:center}",
    ".qbr-scripts-toolbar input[type=search]{flex:1;min-width:200px;padding:7px 10px;font-size:14px}",
    ".qbr-scripts-list{display:flex;flex-direction:column;gap:10px;margin-bottom:16px}",
    ".qbr-scripts-card{border:1px solid #ddd;border-radius:6px;padding:12px 14px}",
    ".qbr-scripts-card h5{margin:0 0 4px;font-size:15px}",
    ".qbr-scripts-badge{font-size:11px;padding:2px 8px;border-radius:10px;margin-left:8px;vertical-align:middle}",
    ".qbr-scripts-badge.bi{background:#d4edda;color:#155724}",
    ".qbr-scripts-badge.cu{background:#d1ecf1;color:#0c5460}",
    ".qbr-scripts-tags{font-size:12px;color:#666;margin:2px 0}",
    ".qbr-scripts-desc{font-size:13px;color:#444;margin:2px 0 8px}",
    ".qbr-scripts-actions{display:flex;gap:8px;flex-wrap:wrap}",
    ".qbr-scripts-form{border:1px solid #ddd;border-radius:6px;padding:14px;margin-bottom:14px;background:#fafafa}",
    ".qbr-scripts-form h4{margin:0 0 6px}",
    ".qbr-scripts-form label{display:block;font-size:13px;font-weight:600;margin:8px 0}",
    ".qbr-scripts-form input,.qbr-scripts-form textarea{width:100%;box-sizing:border-box;padding:7px 9px;font-size:13px;font-weight:400}",
    ".qbr-scripts-form textarea{font-family:Consolas,Menlo,monospace}",
    ".qbr-scripts-gdap{border-top:1px solid #eee;padding-top:12px}",
    ".qbr-scripts-gdap h4{margin:0 0 6px}",
    ".qbr-scripts-note{font-size:12px;color:#666}",
    ".qbr-scripts-toast{position:fixed;bottom:24px;right:24px;background:#1b2a4a;color:#fff;padding:10px 18px;border-radius:6px;font-size:14px;z-index:2001;display:none}"
  ].join("\n");

  function injectCss() {
    if (cssDone) return; cssDone = true;
    var st = document.createElement("style");
    st.textContent = CSS;
    document.head.appendChild(st);
  }

  function currentQuery() {
    return overlay ? overlay.querySelector('[data-sfield="q"]').value : "";
  }

  function renderCards(q) {
    var list = overlay.querySelector("[data-slist]");
    var items = scriptSearch(q);
    if (!items.length) { list.innerHTML = '<p class="qbr-scripts-note">No scripts match.</p>'; return; }
    list.innerHTML = items.map(function (s) {
      return '<div class="qbr-scripts-card" data-sid="' + escHtml(s.id) + '">' +
        "<h5>" + escHtml(s.title) +
        '<span class="qbr-scripts-badge ' + (s.builtin ? "bi" : "cu") + '">' + (s.builtin ? "built-in" : "custom") + "</span></h5>" +
        '<div class="qbr-scripts-tags">' + escHtml(s.tags) + "</div>" +
        '<div class="qbr-scripts-desc">' + escHtml(s.desc) + "</div>" +
        '<div class="qbr-scripts-actions">' +
        '<button type="button" class="btn btn-sm btn-outline-primary" data-sact="copy">Copy</button>' +
        '<button type="button" class="btn btn-sm btn-outline-secondary" data-sact="edit">Edit</button>' +
        (s.builtin ? "" : '<button type="button" class="btn btn-sm btn-outline-danger" data-sact="del">Delete</button>') +
        "</div></div>";
    }).join("");
  }

  function openForm(rec) {
    editingId = rec ? rec.id : null;
    overlay.querySelector("[data-sformtitle]").textContent = rec ? "Edit script" : "Add script";
    overlay.querySelector('[data-sfield="title"]').value = rec ? rec.title : "";
    overlay.querySelector('[data-sfield="tags"]').value = rec ? rec.tags : "";
    overlay.querySelector('[data-sfield="desc"]').value = rec ? rec.desc : "";
    overlay.querySelector('[data-sfield="body"]').value = rec ? rec.body : "";
    overlay.querySelector("[data-sform]").hidden = false;
  }
  function closeForm() { overlay.querySelector("[data-sform]").hidden = true; editingId = null; }

  function saveForm() {
    var val = function (n) { return overlay.querySelector('[data-sfield="' + n + '"]').value; };
    var title = val("title").trim(), body = val("body");
    if (!title || !body.trim()) { alert("Title and script content are required."); return; }
    try {
      scriptUpsert({ id: editingId || ("custom-" + Date.now()), title: title, tags: val("tags").trim(), desc: val("desc").trim(), body: body });
    } catch (e) { alert("Could not save: " + e.message); return; }
    closeForm(); renderCards(currentQuery()); toast("Script saved.");
  }

  function doExport() {
    var blob = new Blob([scriptExport()], { type: "application/json" });
    var a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = "qbr-scripts.json";
    document.body.appendChild(a); a.click(); a.remove();
    setTimeout(function () { URL.revokeObjectURL(a.href); }, 4000);
  }

  function updateGdapStatus() {
    var el = overlay.querySelector("[data-sgdapstatus]");
    if (!el) return;
    var d = (typeof QBR.gdapLoad === "function") ? QBR.gdapLoad() : null;
    el.textContent = (d && d.rows && d.rows.length)
      ? d.rows.length + " schools linked" + (d.savedAt ? " (" + String(d.savedAt).slice(0, 10) + ")" : "") + "."
      : "Not linked.";
  }

  var toastTimer = null;
  function toast(msg) {
    var t = document.getElementById("qbr-scripts-toast");
    if (!t) {
      t = document.createElement("div");
      t.id = "qbr-scripts-toast"; t.className = "qbr-scripts-toast";
      document.body.appendChild(t);
    }
    t.textContent = msg; t.style.display = "block";
    clearTimeout(toastTimer);
    toastTimer = setTimeout(function () { t.style.display = "none"; }, 2200);
  }

  function scriptsOpen() {
    scriptsClose();
    injectCss();
    overlay = document.createElement("div");
    overlay.className = "qbr-scripts-overlay";
    overlay.innerHTML =
      '<div class="qbr-scripts-modal" role="dialog" aria-label="Script library">' +
      '<div class="qbr-scripts-head"><h3>Script library</h3>' +
      '<button type="button" class="btn btn-sm btn-outline-secondary" data-sact="close">Close</button></div>' +
      '<div class="qbr-scripts-toolbar">' +
      '<input type="search" data-sfield="q" placeholder="Search scripts \u2014 try &quot;extract&quot;\u2026" aria-label="Search scripts">' +
      '<button type="button" class="btn btn-sm btn-primary" data-sact="add">+ Add script</button>' +
      '<button type="button" class="btn btn-sm btn-outline-secondary" data-sact="export">Export</button>' +
      '<button type="button" class="btn btn-sm btn-outline-secondary" data-sact="import">Import</button>' +
      '<input type="file" data-sfield="importfile" accept=".json,application/json" hidden>' +
      "</div>" +
      '<div class="qbr-scripts-form" data-sform hidden>' +
      "<h4 data-sformtitle>Add script</h4>" +
      "<label>Title<input data-sfield=\"title\"></label>" +
      "<label>Tags (comma-separated)<input data-sfield=\"tags\" placeholder=\"extract, storage\"></label>" +
      "<label>Description<input data-sfield=\"desc\"></label>" +
      "<label>PowerShell content<textarea data-sfield=\"body\" spellcheck=\"false\" rows=\"10\"></textarea></label>" +
      '<div style="margin-top:8px"><button type="button" class="btn btn-sm btn-primary" data-sact="save">Save</button> ' +
      '<button type="button" class="btn btn-sm btn-outline-secondary" data-sact="cancel">Cancel</button></div>' +
      "</div>" +
      '<div class="qbr-scripts-list" data-slist></div>' +
      '<div class="qbr-scripts-gdap"><h4>GDAP mapping</h4>' +
      '<p class="qbr-scripts-note">CSV with <code>Name,Microsoft ID</code> columns. Used to pre-fill the tenant ID when copying extraction scripts in the wizard. Stored in this browser only.</p>' +
      '<div><input type="file" data-sfield="gdapfile" accept=".csv"> ' +
      '<span class="qbr-scripts-note" data-sgdapstatus></span> ' +
      '<button type="button" class="btn btn-sm btn-outline-secondary" data-sact="gdapclear">Clear</button></div>' +
      "</div>" +
      "</div>";

    overlay.querySelector('[data-sfield="q"]').addEventListener("input", function (e) { renderCards(e.target.value); });
    overlay.querySelector('[data-sfield="importfile"]').addEventListener("change", function (e) {
      var f = e.target.files[0];
      if (!f) return;
      var rd = new FileReader();
      rd.onload = function () {
        try { toast("Imported " + scriptImport(String(rd.result || "")) + " script(s)."); }
        catch (err) { alert("Import failed: " + err.message); }
        renderCards(currentQuery());
      };
      rd.readAsText(f);
      e.target.value = "";
    });
    overlay.querySelector('[data-sfield="gdapfile"]').addEventListener("change", function (e) {
      var f = e.target.files[0];
      if (!f) return;
      var rd = new FileReader();
      rd.onload = function () {
        try {
          var rows = QBR.gdapParseCsv(String(rd.result || ""));
          if (!rows.length) throw new Error("no data rows found.");
          QBR.gdapSave(rows);
          updateGdapStatus();
          toast("GDAP mapping linked: " + rows.length + " schools.");
          if (typeof QBR.refreshGdapChip === "function") QBR.refreshGdapChip();
        } catch (err) { alert("Could not parse that CSV: " + err.message); }
      };
      rd.readAsText(f);
      e.target.value = "";
    });
    overlay.addEventListener("click", function (e) {
      if (e.target === overlay) { scriptsClose(); return; }
      var t = e.target.closest("[data-sact]");
      if (!t) return;
      var act = t.getAttribute("data-sact");
      if (act === "close") scriptsClose();
      else if (act === "add") openForm(null);
      else if (act === "cancel") closeForm();
      else if (act === "save") saveForm();
      else if (act === "export") doExport();
      else if (act === "import") overlay.querySelector('[data-sfield="importfile"]').click();
      else if (act === "gdapclear") { if (typeof QBR.gdapClear === "function") QBR.gdapClear(); updateGdapStatus();  if (typeof QBR.refreshGdapChip === "function") QBR.refreshGdapChip(); }
      else {
        var card = t.closest("[data-sid]");
        var id = card && card.getAttribute("data-sid");
        if (act === "copy") {
          var r = scriptCopyText(id, null);
          if (r) copyToClipboard(r.text).then(function (ok) { toast(ok ? "Copied " + r.title + "." : "Copy failed."); });
        } else if (act === "edit") openForm(scriptGet(id));
        else if (act === "del" && confirm("Delete this script?")) { scriptDelete(id); renderCards(currentQuery()); }
      }
    });
    overlay.addEventListener("keydown", function (e) { if (e.key === "Escape") scriptsClose(); });

    document.body.appendChild(overlay);
    renderCards("");
    updateGdapStatus();
  }

  function scriptsClose() {
    if (overlay && overlay.parentNode) overlay.parentNode.removeChild(overlay);
    overlay = null; editingId = null;
  }

  /* Explicitly exposed entry points (host calls these). */
  QBR.scriptList = scriptList;
  QBR.scriptGet = scriptGet;
  QBR.scriptUpsert = scriptUpsert;
  QBR.scriptDelete = scriptDelete;
  QBR.scriptSearch = scriptSearch;
  QBR.scriptExport = scriptExport;
  QBR.scriptImport = scriptImport;
  QBR.scriptCopyText = scriptCopyText;
  QBR.scriptCopyToClipboard = copyToClipboard;
  QBR.scriptsOpen = scriptsOpen;
  QBR.scriptsClose = scriptsClose;
})();
